"""Add: waiting rooms

Revision ID: 0ef9c2dee84b
Revises: 5af4b11de593
Create Date: 2024-04-21 11:55:36.570094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef9c2dee84b'
down_revision = '5af4b11de593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waiting_room_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'waiting_room', ['waiting_room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('waiting_room_id')

    op.drop_table('waiting_room')
    # ### end Alembic commands ###
