"""Reinit migration

Revision ID: 0f482cd5ded9
Revises: 
Create Date: 2024-04-18 11:59:57.758836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f482cd5ded9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('difficulty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('NORMAL', 'HARD', 'CUSTOM', name='difficultyenum'), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('num_holes', sa.Integer(), nullable=False),
    sa.Column('num_colors', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_multiplayer', sa.Boolean(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'TERMINATED', name='statusenum'), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulty.id'], ),
    sa.ForeignKeyConstraint(['winner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'TERMINATED', name='statusenum'), nullable=False),
    sa.Column('code_breaker', sa.String(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('secret_code', sa.String(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_breaker'], ['user.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_games',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('turn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('turn_num', sa.Integer(), nullable=False),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn')
    op.drop_table('user_games')
    op.drop_table('round')
    op.drop_table('game')
    op.drop_table('user')
    op.drop_table('difficulty')
    # ### end Alembic commands ###
