"""Fix password table char limit

Revision ID: 34d1b87ea507
Revises: a4bb53846f89
Create Date: 2024-04-17 14:33:37.195436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d1b87ea507'
down_revision = 'a4bb53846f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
