"""Add winner backref to Game model

Revision ID: fe00514fa983
Revises: 0cb02f353fcd
Create Date: 2024-04-18 16:07:40.419839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe00514fa983'
down_revision = '0cb02f353fcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner_id', sa.String(), nullable=True))
        batch_op.drop_constraint('game_winner_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['winner_id'], ['id'])
        batch_op.drop_column('winner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('game_winner_fkey', 'user', ['winner'], ['id'])
        batch_op.drop_column('winner_id')

    # ### end Alembic commands ###
